INSERT INTO TIPO_USUARIO(descricao) VALUES ('PROFESSOR');
INSERT INTO TIPO_USUARIO(descricao) VALUES ('ALUNO');

INSERT INTO CONDUTOR(EMAIL,NOME,REGISTRO,TELEFONE,VAGA_ESPECIAL,TIPO_USUARIO_ID) VALUES ('professor@utfpr.edu.br','Professor','001','4612345678',false,1);
INSERT INTO CONDUTOR(EMAIL,NOME,REGISTRO,TELEFONE,VAGA_ESPECIAL,TIPO_USUARIO_ID) VALUES ('aluno@utfpr.edu.br','Aluno','002','4612345678',false,2);

INSERT INTO PERMISSAO(permissao) VALUES ('ROLE_ADMIN');
INSERT INTO PERMISSAO(permissao) VALUES ('ROLE_USER');

INSERT INTO USUARIO(nome, username, password, TIPO_USUARIO_ID, CONDUTOR_ID) VALUES ('Administrador','admin','$2a$10$.PVIfB07x.SfMYTcToxL0.yxcLWU0GbS2NUO1W1QAvqMm/TsFhVem',1,1);
INSERT INTO USUARIO(nome, username, password, TIPO_USUARIO_ID, CONDUTOR_ID) VALUES ('Teste', 'teste','$2a$10$.PVIfB07x.SfMYTcToxL0.yxcLWU0GbS2NUO1W1QAvqMm/TsFhVem',2,2);

INSERT INTO USUARIO_PERMISSOES(usuario_id, permissoes_id) VALUES (1, 1);
INSERT INTO USUARIO_PERMISSOES(usuario_id, permissoes_id) VALUES (2, 2);

INSERT INTO MARCA(ID, NOME, TIPO) VALUES (1, 'VW', 'C');
INSERT INTO MARCA(ID, NOME, TIPO) VALUES (2, 'Fiat', 'C');

INSERT INTO MODELO(ID, NOME, MARCA_ID) VALUES (1, 'Fusca', 1);
INSERT INTO MODELO(ID, NOME, MARCA_ID) VALUES (2, '147', 2);