server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
          persistence:
              validation:
                mode: none
      hibernate:
          format_sql: true
    show-sql: true
    data:
      web:
        pageable:
          default-page-size: 10
          max-page-size: 100
  flyway:
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
minio:
  endpoint: http://localhost:9000
  url: http://localhost
  port: 9000
  accessKey:  minioadmin #Login Account
  secretKey:  minioadmin # Login Password
  secure: false
  bucket-name: commons # Bucket Name
  image-size: 10485760 #  Maximum size of picture file
  file-size: 1073741824 #  Maximum file size
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:pw26s-prod
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  flyway:
    locations: classpath:/db/prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:pw26s-dev
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/dev
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    locations: classpath:/db/test